/*
 * libFuzzer harness for ngx_http_error_abuse_parse_statuses().
 *
 * Why this target: it parses a free-form "403,404,500-599"-style status
 * list with ngx_strlchr / ngx_atoi and pointer arithmetic, then for every
 * status in each [first,final] range sets a bit:
 *
 *     zone->statuses[status >> 3] |= 1U << (status & 7);
 *
 * That is an OOB-WRITE surface: if the (first<100 / final<first /
 * final>MAX_STATUS) guard is ever weakened, `status >> 3` walks past the
 * fixed-size statuses[] bitmap. ASAN turns that into an immediate, repro-
 * ducible heap-buffer-overflow. The fuzzer feeds the raw list bytes; the
 * harness places the bitmap right at the end of an exact-sized allocation
 * so any single-byte over-write is caught.
 *
 * The real function lives in ../ngx_http_error_abuse_module.c. extract_
 * parser.sh slices it verbatim into generated_parser.inc at build time,
 * so we always fuzz the SHIPPED parser with no copy drift. ngx_shim.h
 * supplies ngx_strlchr / ngx_atoi (faithful upstream copies) and the
 * no-op conf-log sink.
 *
 * Build (see fuzz/build.sh):
 *   clang -g -O1 -fsanitize=fuzzer,address,undefined \
 *       fuzz_statuses.c -o fuzz_statuses
 */

#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>

#include "ngx_shim.h"

/* Generated by fuzz/extract_parser.sh — verbatim bodies of
 * parse_statuses() and validate_snapshot(). We only call the former. */
#include "generated_parser.inc"

int
LLVMFuzzerTestOneInput(const uint8_t *data, size_t size)
{
    /*
     * Put the zone (whose tail is the statuses[] bitmap) on the heap so
     * ASAN red-zones bracket it: any write past statuses[STATUS_BYTES-1]
     * is an immediate heap-buffer-overflow rather than silent corruption
     * of an adjacent stack slot.
     */
    ngx_http_error_abuse_zone_t *zone =
        (ngx_http_error_abuse_zone_t *) calloc(1, sizeof(*zone));
    if (zone == NULL) {
        return 0;
    }
    zone->threshold = 100;   /* unused by parse_statuses, kept sane */

    /*
     * The list bytes are NOT NUL-terminated: the parser is fully length-
     * bounded (value->data .. value->data+value->len), so feed exactly
     * `size` bytes and let ASAN flag any read past the end. Allocate at
     * least one byte (never NULL) — in production value->data is always a
     * real config-string buffer, so a NULL here would only trip a bogus
     * "NULL + 0" UBSan report that cannot happen for real input.
     */
    size_t  alloc = size ? size : 1;
    u_char *buf = (u_char *) malloc(alloc);
    if (buf == NULL) { free(zone); return 0; }
    if (size) {
        memcpy(buf, data, size);
    }

    ngx_str_t value;
    value.data = buf;
    value.len  = size;

    ngx_int_t rc = ngx_http_error_abuse_parse_statuses(
                       (ngx_conf_t *) NULL, zone, &value);

    /* Contract: only NGX_OK or NGX_ERROR. Anything else means a path fell
     * through somewhere it should not have. */
    if (rc != NGX_OK && rc != NGX_ERROR) {
        __builtin_trap();
    }

    free(buf);
    free(zone);
    return 0;
}
